### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DorraJaouad** [DorraJaouad/scholarship-roulette#2]
- [x] Add all countries list
- [x] Fix the navigation menu
- [x] Check deployment
- [x] Secure the DB
- [x] Add Home content
- [x] Fix wording (in modal)
